---
extends: default
ignore: |
  /.github/METADATA.yaml
  /dist/**
  /.github/stale.yml
  /.github/workflows/lock.yml
  /.github/config.yml
  /.github/dependabot.yml
  /taskfiles/Taskfile.devex.yml
rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  comments:
    level: warning
    require-starting-space: true
    min-spaces-from-content: 2
  truthy: disable
  indentation: enable
  key-duplicates: enable
  trailing-spaces: enable
  new-line-at-end-of-file: enable
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: true
  line-length:
    max: 100
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
