---
name: Go Build
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  build-supported-platforms:
    name: Go Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64, arm]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ~1.20
      - name: Build for ${{ matrix.goos }}/${{ matrix.goarch }}
        run: make build GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }}
  build-supported-go-version:
    name: Go Build Versions
    needs: build-supported-platforms
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go-versions: [~1.20, ~1.21]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-versions }}
      - name: Build for ${{ matrix.go-versions }}
        run: make build GOOS=linux GOARCH=amd64
