---
name: Go Build
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  build-supported-platforms:
    name: Go Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platforms: [linux/amd64, linux/arm64, linux/arm/v7, windows/amd64, darwin/amd64]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build for ${{ matrix.platforms }}
        run: make build GOOS=${{ matrix.platforms }}
  build-supported-go-version:
    name: Go Build Versions
    needs:
      - build-supported-platforms
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go-versions: [~1.20, ~1.21, ~1.22]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-versions }}
      - name: Build for ${{ matrix.go-versions }}
        run: make build GOOS=linux GOARCH=amd64
